name: qr_scanner_app
description: A smart QR scanner app built using Flutter.

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^7.0.1
  url_launcher: ^6.3.1
  clipboard: ^0.1.3
  fluttertoast: ^8.2.12
  vibration: ^3.1.3
  image_picker: ^1.1.2
  google_mlkit_barcode_scanning: ^0.14.1
  animated_text_kit: ^4.2.3
  flutter_animate: ^4.5.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
